### ISSUE TITLE
May I Add Flutter App(News App) with Code and detailed explanation

### ISSUE THREAD

**Issue by ShivamChoudhary17** [aman1210/Hacktoberfest2021#90]
This News app fetch data from Inshorts News API and display it in different sections like world, business, automobiles, trade, politics , start-ups and different national news etc.

May I Start working on it?
Thank You!

**Comment by aman1210** [comment]
Hi @ShivamChoudhary17 
Sure, go ahead with it.

**Comment by ShivamChoudhary17** [comment]
@aman1210 
Done #135

Thanks!
